version: '3.8'

services:
  app:
    image: docker.io/bitnami/laravel:10
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - "DB_CONNECTION=sqlite"
      - "DB_DATABASE=/app/database/database.sqlite"
    ports:
      - "8000:8000"